package com.myspace.dronerentalboiz;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerFeedback implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Text description of customer feedback")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Customer email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("Customer rating of our service (1-10)")
	private java.lang.Integer rating;
	@org.kie.api.definition.type.Label("Customer suggestions what we can improve")
	private java.lang.String tips;

	public CustomerFeedback() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.Integer getRating() {
		return this.rating;
	}

	public void setRating(java.lang.Integer rating) {
		this.rating = rating;
	}

	public java.lang.String getTips() {
		return this.tips;
	}

	public void setTips(java.lang.String tips) {
		this.tips = tips;
	}

	public CustomerFeedback(java.lang.String description,
			java.lang.String email, java.lang.Integer rating,
			java.lang.String tips) {
		this.description = description;
		this.email = email;
		this.rating = rating;
		this.tips = tips;
	}

}