package com.myspace.dronerentalboiz;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerSupportTicket implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("Subject of the ticket")
	private java.lang.String subject;
	@org.kie.api.definition.type.Label("Description of the issue")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("what is the priority of reported issue (1-5)")
	private java.lang.Integer priority;
	@org.kie.api.definition.type.Label("Additional information if needed")
	private java.lang.String additionalInfo;

	public CustomerSupportTicket() {
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Integer getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Integer priority) {
		this.priority = priority;
	}

	public java.lang.String getAdditionalInfo() {
		return this.additionalInfo;
	}

	public void setAdditionalInfo(java.lang.String additionalInfo) {
		this.additionalInfo = additionalInfo;
	}

	public CustomerSupportTicket(java.lang.String email,
			java.lang.String subject, java.lang.String description,
			java.lang.Integer priority, java.lang.String additionalInfo) {
		this.email = email;
		this.subject = subject;
		this.description = description;
		this.priority = priority;
		this.additionalInfo = additionalInfo;
	}

}