package com.myspace.dronerentalboiz;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class emailTemplate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("Description what is  needed")
	private java.lang.String body;
	@org.kie.api.definition.type.Label("email subject")
	private java.lang.String subject;

	public emailTemplate() {
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getBody() {
		return this.body;
	}

	public void setBody(java.lang.String body) {
		this.body = body;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public emailTemplate(java.lang.String email, java.lang.String body,
			java.lang.String subject) {
		this.email = email;
		this.body = body;
		this.subject = subject;
	}

}