package com.myspace.dronerentalboiz;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TicketReport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("What was done and why it was needed")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("How severe was the issue for customer")
	private java.lang.Integer impact;
	@org.kie.api.definition.type.Label("Who was handling the ticket")
	private java.lang.String resolvedBy;
	@org.kie.api.definition.type.Label("Link to related CS ticket")
	private java.lang.String linkToTicket;

	public TicketReport() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Integer getImpact() {
		return this.impact;
	}

	public void setImpact(java.lang.Integer impact) {
		this.impact = impact;
	}

	public java.lang.String getResolvedBy() {
		return this.resolvedBy;
	}

	public void setResolvedBy(java.lang.String resolvedBy) {
		this.resolvedBy = resolvedBy;
	}

	public java.lang.String getLinkToTicket() {
		return this.linkToTicket;
	}

	public void setLinkToTicket(java.lang.String linkToTicket) {
		this.linkToTicket = linkToTicket;
	}

	public TicketReport(java.lang.String description, java.lang.Integer impact,
			java.lang.String resolvedBy, java.lang.String linkToTicket) {
		this.description = description;
		this.impact = impact;
		this.resolvedBy = resolvedBy;
		this.linkToTicket = linkToTicket;
	}

}